title: Scriptorite
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5
posts: "/posts"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

disqus: scripta-mirabilia
