title: Scripta Mirabilia
url: 
remote_theme: chesterhow/tale

permalink:    posts/:year-:month-:day/:title
paginate:     5
posts: "/posts"

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

disqus: scripta-mirabilia
