title: Scripta Mirabilia
remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5
paginate-path: /posts/

plugins:
  - jekyll-paginate
  - jekyll-remote-theme

disqus: scripta-mirabilia
